# Generated by Django 5.2.6 on 2025-09-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('card_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('type', models.CharField(blank=True, choices=[('creature', 'Creature'), ('spell', 'Spell'), ('artifact', 'Artifact'), ('land', 'Land')], max_length=50)),
                ('rarity', models.CharField(blank=True, choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('mythic', 'Mythic')], max_length=50)),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('blue', 'Blue'), ('black', 'Black'), ('red', 'Red'), ('green', 'Green'), ('colorless', 'Colorless')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
