# Generated by Django 5.2.6 on 2025-09-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_id',
        ),
    ]
