# Generated by Django 5.2.6 on 2025-10-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_card_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='type',
            new_name='card_type',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rarity',
        ),
        migrations.AddField(
            model_name='card',
            name='card_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
