# Generated by Django 5.2.6 on 2025-10-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_type_card_card_type_remove_card_rarity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_description',
            field=models.TextField(blank=True),
        ),
    ]
