# Generated by Django 5.2.6 on 2025-10-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_card_card_type_alter_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(blank=True, choices=[('creature', 'Creature'), ('spell', 'Spell'), ('artifact', 'Artifact'), ('land', 'Land')], max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('blue', 'Blue'), ('black', 'Black'), ('red', 'Red'), ('green', 'Green'), ('colorless', 'Colorless')], max_length=50),
        ),
    ]
